# Generated by Django 5.1.7 on 2025-04-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediFundapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='fund_raising_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_info', models.CharField(blank=True, max_length=255)),
                ('user_id', models.IntegerField()),
                ('user_qualification', models.CharField(blank=True, max_length=255)),
                ('user_employed_status', models.CharField(blank=True, max_length=255)),
                ('how_to_know', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(max_length=50)),
                ('fund_title', models.CharField(blank=True, max_length=255)),
                ('fund_purpose', models.TextField(blank=True)),
                ('fund_for', models.CharField(blank=True, max_length=255)),
                ('fund_raising_amount', models.IntegerField()),
                ('amount_raised', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=50)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('ngo_name', models.CharField(blank=True, max_length=255)),
                ('ngo_registration_number', models.CharField(blank=True, max_length=255)),
                ('ngo_website_url', models.URLField(blank=True)),
                ('patienet_full_name', models.CharField(blank=True, max_length=255)),
                ('patienet_age', models.IntegerField(blank=True, null=True)),
                ('hospitalization_status', models.CharField(blank=True, max_length=255)),
                ('hospital_name', models.CharField(blank=True, max_length=255)),
                ('hospital_location', models.CharField(blank=True, max_length=255)),
                ('animal_type', models.CharField(blank=True, max_length=255)),
                ('animal_name', models.CharField(blank=True, max_length=255)),
                ('animal_age', models.IntegerField(blank=True, null=True)),
                ('treatment_reason', models.TextField(blank=True)),
                ('vetnairy_name', models.CharField(blank=True, max_length=255)),
                ('vetnairy_clinic_name', models.CharField(blank=True, max_length=255)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('medical_documents', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('patienet_image', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_date', models.DateField()),
                ('created_by', models.CharField(max_length=255)),
                ('last_created_date', models.DateField(null=True)),
                ('last_created_by', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='patient_page_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paitient_full_name', models.CharField(max_length=255)),
                ('paitient_age', models.IntegerField(max_length=999999999999999)),
                ('hospitalisation_status', models.CharField(unique=True)),
                ('hospital', models.CharField(max_length=35, unique=True)),
                ('enter_city', models.CharField(max_length=35, unique=True)),
                ('user_emp_status', models.CharField(max_length=255)),
                ('how_to_know', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='patient_story_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patienet_story', models.TextField()),
                ('attachments', models.TextField(default='zxcvbnm')),
            ],
        ),
        migrations.CreateModel(
            name='raising_fund_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_purpose', models.CharField(max_length=255)),
                ('fund_raising_amount', models.IntegerField(max_length=999999999999999)),
                ('fund_title', models.CharField(unique=True)),
                ('fund_for', models.CharField(max_length=35, unique=True)),
                ('user_qualification', models.CharField(max_length=35, unique=True)),
                ('user_emp_status', models.CharField(max_length=255)),
                ('how_to_know', models.CharField(max_length=255)),
                ('attachments', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.TextField(max_length=35)),
                ('mobile_number', models.BigIntegerField()),
                ('creation_purpose', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Case',
        ),
        migrations.DeleteModel(
            name='Compaign',
        ),
        migrations.DeleteModel(
            name='Contribution',
        ),
        migrations.DeleteModel(
            name='Donation_tip',
        ),
        migrations.DeleteModel(
            name='Party',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.RemoveField(
            model_name='medicallead',
            name='attributes1',
        ),
        migrations.RemoveField(
            model_name='medicallead',
            name='attributes2',
        ),
        migrations.RemoveField(
            model_name='medicallead',
            name='attributes3',
        ),
        migrations.RemoveField(
            model_name='medicallead',
            name='attributes4',
        ),
        migrations.RemoveField(
            model_name='medicallead',
            name='attributes5',
        ),
        migrations.RemoveField(
            model_name='medicallead',
            name='cb',
        ),
        migrations.RemoveField(
            model_name='medicallead',
            name='cd',
        ),
        migrations.RemoveField(
            model_name='medicallead',
            name='lub',
        ),
        migrations.RemoveField(
            model_name='medicallead',
            name='lud',
        ),
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='attribute1',
        ),
        migrations.RemoveField(
            model_name='user',
            name='attribute2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='attribute3',
        ),
        migrations.RemoveField(
            model_name='user',
            name='attribute4',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cb',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cd',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='education',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lub',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lud',
        ),
        migrations.RemoveField(
            model_name='user',
            name='occupation',
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
