# Generated by Django 5.1.7 on 2025-04-25 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MediFundapp', '0002_fund_raising_form_login_patient_page_info_and_more'),
    ]

    operations = [
    ]
