# Generated by Django 5.1.7 on 2025-04-25 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MediFundapp', '0003_cleanup_temp'),
    ]

    operations = [
    ]
